/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 끝난 거래 목록
         * @description 조건에 드는 거래를 진입 시각 오름차순으로 낸다
         */
        get: operations["closedTrades"];
        put?: never;
        /**
         * 진입 전 계획 저장
         * @description 진입하기 전에 남긴다. 진입 후에 적으면 결과를 아는 채로 쓰게 되고,
         *     그런 기록으로는 계획 준수 여부를 판정할 수 없다.
         */
        post: operations["plan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trades/{id}/fills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 진입 체결 기록
         * @description 체결 내역과 진입 시점의 시장 상태를 함께 받는다. 맥락은 이 순간에만 존재한다.
         */
        post: operations["recordFills"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trades/{id}/closure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 청산 기록
         * @description 손익은 받지 않는다. 청산가와 체결 내역으로 도메인이 계산한다.
         */
        post: operations["close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projections/monte-carlo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 같은 조건 N 회 반복의 결과 분포
         * @description 기댓값이 같아도 경로에 따라 결과가 갈린다. 하위 5% 와 상위 5% 의 간격,
         *     그리고 최대낙폭 분포가 그 차이를 수치로 보여준다.
         */
        post: operations["monteCarlo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projections/equity-curve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 시드 하나가 만드는 표본 자산 곡선
         * @description 승패 순서를 시드로 뽑아 자산 곡선 하나를 그린다.
         *     같은 시드는 항상 같은 곡선을 낸다.
         */
        post: operations["equityCurve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/position-plans/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 분할 진입 계획의 체결 상태별 리스크 산출
         * @description 1건 체결부터 전량 체결까지 각 시점의 평단·수량·청산가·최대손실을 낸다.
         *     수량은 요청에 없다 — 손절가와 리스크 비율이 수량을 결정하기 때문이다.
         */
        post: operations["analyze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/markets/{symbol}/candles/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 거래소에서 받아 증분 저장
         * @description 이미 저장된 시각은 다시 세지 않는다. 같은 구간을 두 번 수집하면
         *     두 번째 응답의 newlyStored 는 0 이다.
         */
        post: operations["sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 백테스트 실행
         * @description 피벗 군집으로 만든 대의 근단에서 반전 방향으로 50% 분할 진입하고,
         *     대 원단 너머에서 손절하며, 반대편 최근접 대에서 익절한다.
         *     한 봉 안에서 손절과 익절이 모두 닿으면 손절로 처리한다 —
         *     OHLC 로는 봉 내부 경로를 알 수 없으므로 보유자에게 불리한 쪽을 택한다.
         */
        post: operations["run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/narrative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 백테스트 결과 요약 (AI)
         * @description 같은 조건으로 백테스트를 돌리고 그 수치를 한국어 몇 문장으로 옮긴다.
         *     요약에 나오는 수는 전부 응답의 facts 안에 있는 값이며,
         *     없는 수가 들어간 요약은 만들어지지 않고 503 이 된다.
         *
         *     /api/ai 아래에 있지 않은 이유는 모듈 순환 때문이다 — ai 가 백테스트를
         *     직접 돌리면 backtest 와 ai 가 서로를 참조하게 되고 ArchUnit 규칙 3 이
         *     빌드를 세운다. 사실을 만들어 넘기는 쪽이 백테스트다.
         *
         *     앞으로 어떻게 하라는 말은 하지 않는다. 근거는 docs/adr/005.
         */
        post: operations["narrate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/indicator-filter-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 지표 필터 온오프 비교
         * @description 같은 캔들로 두 번 돌린다 — 일목·볼린저를 게이트로 쓴 실행과 쓰지 않은 실행.
         *     필터가 실제로 값을 하는지는 비교로만 답할 수 있는 질문이다.
         *     요청의 indicatorFilter 값은 무시된다.
         */
        post: operations["compareIndicatorFilter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/cost-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 비용 유무 비교
         * @description 같은 체결에 비용만 다르게 두 번 돌린다.
         *     수수료가 엣지를 먹어 치우는지 — 전략이 이겼는데 계좌가 줄어드는지 — 를 낸다.
         */
        post: operations["compareCosts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 매매 기록 재색인
         * @description 청산된 거래 전부로 색인을 다시 만든다. 문서 형식이나 임베딩 모델이 바뀌면
         *     이것 없이는 과거 기록이 구버전으로 남는다.
         *
         *     청산 시에는 자동으로 색인되므로 평소에는 부를 일이 없다.
         *     색인은 파생 데이터이고 진실의 원천은 매매 기록이므로,
         *     언제 몇 번을 불러도 기록이 달라지지 않는다.
         */
        post: operations["reindex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/plan-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 자연어 → 매매 계획 초안
         * @description 문장에 있는 값만 옮겨 적는다. 없는 값은 추측해서 채우지 않고
         *     무엇이 없는지 되물어 온다 — 잘못 채운 진입가는 잘못된 포지션 사이즈로
         *     이어지고 그 오류는 계산 계층 전체를 조용히 오염시킨다.
         *
         *     총수량은 초안에 없다. 수량은 손절가와 리스크 예산이 결정하는 값이므로
         *     /api/position-plans/analysis 가 계산한다.
         */
        post: operations["draftPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/journal-query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 매매 기록 질의
         * @description 지난 매매 기록에서 질문에 가까운 거래를 찾아 그것만 근거로 답한다.
         *     답변과 함께 근거 거래 식별자가 내려오므로 원본 기록과 대조할 수 있다.
         *     검색 결과가 없으면 모델을 부르지 않고 "해당하는 기록이 없다" 를 돌려준다 —
         *     없는 것에 대해 문장을 만들 기회 자체를 주지 않는다.
         *
         *     "손실 직후에 들어간 거래" 처럼 순서를 묻는 질문에 답할 수 있는 이유는
         *     색인 시점에 그 사실을 미리 계산해 두기 때문이다. 유사도만으로는
         *     "직후" 를 찾을 수 없다.
         *
         *     앞으로의 매매는 묻지 않는다. 이미 일어난 일에 대해서만 답한다.
         */
        post: operations["askJournal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trades/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 거래 한 건 조회 */
        get: operations["trade"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trades/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 집계
         * @description 목록과 같은 조건이 걸린다. 계획 준수 쪽과 위반 쪽을 갈라서 낸다.
         */
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trades/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 진행 중인 거래
         * @description 세워 둔 계획과 아직 닫히지 않은 포지션
         */
        get: operations["activeTrades"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/markets/{symbol}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 펀딩비·미결제약정·롱숏비율
         * @description 세 값을 한 시점으로 묶어 돌려준다. 따로 조회하면 서로 다른 시각의 값을
         *     나란히 놓고 판단하게 된다.
         */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/markets/{symbol}/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 저장된 캔들 조회
         * @description 거래소를 때리지 않는다. 이미 저장된 것만 돌려준다.
         *     구간은 반열림 [from, to) 이라 연속 조회에서 경계 캔들이 겹치지 않는다.
         */
        get: operations["candles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 기록과 거래소 포지션 대조
         * @description 기록의 미청산 거래와 거래소의 실제 포지션을 방향으로 맞춰 본다.
         *
         *     거래소 값으로 기록을 덮어쓰지 않는다. 기록은 내가 무엇을 하려 했는지를 알고
         *     거래소는 지금 무엇이 열려 있는지를 안다 — 어느 쪽도 다른 쪽을 대체하지 못한다.
         *
         *     가장 잡고 싶은 것은 RECORDED_ONLY 다. 손절이 체결됐는데 청산을 적지 않으면
         *     그 상태가 되고, 그동안 집계는 그 거래를 없는 것으로 센다.
         */
        get: operations["positions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 분할 진입 한 회차. 비중의 합은 정확히 100 이어야 한다 */
        PlannedEntryRequest: {
            /**
             * @description 이 회차의 지정가
             * @example 60000
             */
            price?: number;
            /**
             * @description 이 회차에 넣을 비중. 50 은 50% 를 뜻한다
             * @example 50
             */
            allocation?: number;
        };
        /**
         * @description 진입 전 매매 계획
         * @example {
         *       "direction": "LONG",
         *       "entries": [
         *         {
         *           "price": 60000,
         *           "allocation": 50
         *         },
         *         {
         *           "price": 59000,
         *           "allocation": 50
         *         }
         *       ],
         *       "stopLoss": 58000,
         *       "takeProfit": 64000,
         *       "leverage": 10
         *     }
         */
        TradePlanRequest: {
            /**
             * @description 포지션 방향
             * @example LONG
             * @enum {string}
             */
            direction?: "LONG" | "SHORT";
            /** @description 분할 진입 계획. 50% 분할이면 2건 */
            entries?: components["schemas"]["PlannedEntryRequest"][];
            /**
             * @description 손절가. 롱은 최저 진입가보다 낮아야 한다
             * @example 58000
             */
            stopLoss?: number;
            /**
             * @description 익절가. 롱은 최고 진입가보다 높아야 한다
             * @example 64000
             */
            takeProfit?: number;
            /**
             * Format: int32
             * @description 레버리지 배수
             * @example 10
             */
            leverage?: number;
        };
        /** @description 분할 진입 한 회차 */
        EntryResponse: {
            /**
             * @description 지정가
             * @example 60000
             */
            price: number;
            /**
             * @description 비중 (%)
             * @example 50
             */
            allocation: number;
        };
        /** @description 실제 진입 결과와 그때의 시장 상태 */
        EntryResultResponse: {
            /**
             * Format: date-time
             * @description 포지션이 열린 시각. 첫 체결이다
             * @example 2026-08-01T01:00:00Z
             */
            openedAt: string;
            /**
             * Format: int32
             * @description 체결 회차 수. 계획보다 적으면 분할이 다 채워지지 않은 것이다
             * @example 2
             */
            fillCount: number;
            /**
             * @description 수량 가중 평균 진입가. 계획 평단과의 차이가 슬리피지다
             * @example 59500
             */
            averageEntryPrice: number;
            /**
             * @description 총 체결 수량 (BTC)
             * @example 0.1
             */
            quantity: number;
            /**
             * @description 진입 판단 시점의 가격
             * @example 60000
             */
            priceAtEntry: number;
            /**
             * @description 일목 구름 대비 위치
             * @example ABOVE
             * @enum {string}
             */
            ichimokuPosition: "ABOVE" | "INSIDE" | "BELOW";
            /**
             * @description 볼린저 밴드 대비 위치
             * @example INSIDE
             * @enum {string}
             */
            bollingerPosition: "ABOVE" | "INSIDE" | "BELOW";
            /**
             * @description 진입 근거
             * @example 4h 59,000 지지 3회 확인
             */
            rationale: string;
        };
        /** @description 청산 결과와 반사실 */
        OutcomeResponse: {
            /**
             * Format: date-time
             * @description 청산 시각
             * @example 2026-08-01T09:00:00Z
             */
            closedAt: string;
            /**
             * @description 청산 체결가
             * @example 64000
             */
            exitPrice: number;
            /**
             * @description 왜 닫았는가
             * @example PLANNED_TARGET
             * @enum {string}
             */
            exitReason: "PLANNED_STOP" | "PLANNED_TARGET" | "MANUAL_EARLY" | "HELD_PAST_STOP" | "LIQUIDATED";
            /**
             * @description 계획대로 닫혔는가. 손실이어도 참일 수 있다
             * @example true
             */
            followedPlan: boolean;
            /**
             * @description 포지션을 들고 있던 시간 (ISO-8601)
             * @example PT8H
             */
            holdingPeriod: string;
            /**
             * @description 비용 전 손익 (USDT)
             * @example 450
             */
            grossPnl: number;
            /**
             * @description 수수료와 펀딩비를 뺀 실현 손익 (USDT)
             * @example 443.8
             */
            realizedPnl: number;
            /**
             * @description 손절을 지켰다면 났을 손익. 실제 청산가·보유 기간과 무관하다
             * @example -155
             */
            lossIfStopHonored: number;
            /**
             * @description 계획을 어겨서 얻은 것. 음수면 어긴 대가다
             * @example 598.8
             */
            costOfDeviation: number;
        };
        /** @description 진입 전에 세운 계획 */
        PlanResponse: {
            /**
             * @description 포지션 방향
             * @example LONG
             * @enum {string}
             */
            direction: "LONG" | "SHORT";
            /** @description 분할 진입 계획. 순서가 진입 순서다 */
            entries: components["schemas"]["EntryResponse"][];
            /**
             * @description 계획한 손절가
             * @example 58000
             */
            stopLoss: number;
            /**
             * @description 계획한 익절가
             * @example 64000
             */
            takeProfit: number;
            /**
             * Format: int32
             * @description 레버리지 배수
             * @example 10
             */
            leverage: number;
            /**
             * @description 표시용 손익비. 버림이라 1.50 이상이면 경고 기준을 넘긴 것이다
             * @example 3
             */
            riskRewardRatio: number;
            /**
             * @description 손익비가 1.5 미만인가. 경고일 뿐 거부하지 않는다
             * @example false
             */
            weakRiskReward: boolean;
        };
        /** @description 거래 한 건. state 에 따라 entry / outcome 이 비어 있다 */
        TradeResponse: {
            /**
             * Format: uuid
             * @description 거래 식별자
             * @example 2f1c4e6a-0000-4000-8000-000000000001
             */
            id: string;
            /**
             * @description PLANNED / OPEN / CLOSED
             * @example CLOSED
             */
            state: string;
            /**
             * Format: date-time
             * @description 계획을 세운 시각
             * @example 2026-08-01T00:00:00Z
             */
            plannedAt: string;
            /** @description 진입 전에 세운 계획 */
            plan: components["schemas"]["PlanResponse"];
            /** @description 실제 진입 결과. PLANNED 상태에서는 null */
            entry: components["schemas"]["EntryResultResponse"] | null;
            /** @description 청산 결과. CLOSED 상태에서만 존재 */
            outcome: components["schemas"]["OutcomeResponse"] | null;
        };
        /** @description 체결 한 건 */
        FillRequest: {
            /**
             * @description 실제 체결가. 계획한 지정가와 다를 수 있다
             * @example 60000
             */
            price?: number;
            /**
             * @description 체결 수량 (BTC)
             * @example 0.05
             */
            quantity?: number;
            /**
             * Format: date-time
             * @description 체결 시각 (UTC)
             * @example 2026-08-01T01:00:00Z
             */
            at?: string;
        };
        /** @description 진입 시점의 시장 상태 */
        MarketContextRequest: {
            /**
             * @description 진입 판단을 내린 시점의 가격
             * @example 60000
             */
            priceAtEntry?: number;
            /**
             * @description 일목 구름 대비 위치
             * @example ABOVE
             * @enum {string}
             */
            ichimokuPosition?: "ABOVE" | "INSIDE" | "BELOW";
            /**
             * @description 볼린저 밴드 대비 위치
             * @example INSIDE
             * @enum {string}
             */
            bollingerPosition?: "ABOVE" | "INSIDE" | "BELOW";
            /**
             * @description 왜 들어갔는가. 비워 둘 수 없다 — 근거 없는 기록은 분석에 쓸 수 없다
             * @example 4h 59,000 지지 3회 확인
             */
            rationale?: string;
        };
        /**
         * @description 진입 체결과 그때의 시장 상태
         * @example {
         *       "fills": [
         *         {
         *           "price": 60000,
         *           "quantity": 0.05,
         *           "at": "2026-08-01T01:00:00Z"
         *         },
         *         {
         *           "price": 59000,
         *           "quantity": 0.05,
         *           "at": "2026-08-01T02:00:00Z"
         *         }
         *       ],
         *       "context": {
         *         "priceAtEntry": 60000,
         *         "ichimokuPosition": "ABOVE",
         *         "bollingerPosition": "INSIDE",
         *         "rationale": "4h 59,000 지지 3회 확인"
         *       }
         *     }
         */
        RecordFillsRequest: {
            /** @description 체결 내역. 시간 오름차순이어야 한다 */
            fills?: components["schemas"]["FillRequest"][];
            /** @description 진입 시점의 시장 상태 */
            context?: components["schemas"]["MarketContextRequest"];
        };
        /**
         * @description 포지션 청산 기록
         * @example {
         *       "exitPrice": 64000,
         *       "exitAt": "2026-08-01T09:00:00Z",
         *       "exitReason": "PLANNED_TARGET",
         *       "fees": 5,
         *       "funding": 1.2
         *     }
         */
        CloseTradeRequest: {
            /**
             * @description 청산 체결가
             * @example 64000
             */
            exitPrice?: number;
            /**
             * Format: date-time
             * @description 청산 시각 (UTC). 마지막 진입 체결보다 앞설 수 없다
             * @example 2026-08-01T09:00:00Z
             */
            exitAt?: string;
            /**
             * @description 왜 닫았는가. 계획 준수 여부가 이 값으로 갈린다
             * @example PLANNED_TARGET
             * @enum {string}
             */
            exitReason?: "PLANNED_STOP" | "PLANNED_TARGET" | "MANUAL_EARLY" | "HELD_PAST_STOP" | "LIQUIDATED";
            /**
             * @description 이 거래에 나간 수수료 (USDT). 음수일 수 없다
             * @example 5
             */
            fees?: number;
            /**
             * @description 낸 펀딩비 (USDT). 받았으면 음수
             * @example 1.2
             */
            funding?: number;
        };
        /**
         * @description 몬테카를로 시뮬레이션 요청
         * @example {
         *       "spec": {
         *         "initialCapital": 800,
         *         "winRate": 45,
         *         "riskRewardRatio": 2,
         *         "riskPerTrade": 2,
         *         "tradesPerWeek": 2,
         *         "weeks": 50
         *       },
         *       "runs": 1000,
         *       "seed": 20260821
         *     }
         */
        MonteCarloRequest: {
            /** @description 시뮬레이션 조건 */
            spec?: components["schemas"]["ProjectionSpecRequest"];
            /**
             * Format: int32
             * @description 시행 횟수. 1 이상 10000 이하
             * @example 1000
             */
            runs?: number;
            /**
             * Format: int64
             * @description 난수 시드. 같은 시드는 항상 같은 분포를 만든다
             * @example 20260821
             */
            seed?: number;
        };
        /** @description 복리 시뮬레이션 조건 */
        ProjectionSpecRequest: {
            /**
             * @description 시작 자산 (USDT)
             * @example 800
             */
            initialCapital?: number;
            /**
             * @description 승률. 45 는 100 번 중 45 번 이긴다는 뜻이다
             * @example 45
             */
            winRate?: number;
            /**
             * @description 손익비. 이겼을 때 버는 폭이 졌을 때 잃는 폭의 몇 배인가
             * @example 2
             */
            riskRewardRatio?: number;
            /**
             * @description 거래 한 건에 거는 현재 자산의 비율. 2 는 2% 를 뜻한다. 고정 금액이 아니라 비율이라 자산이 늘면 거는 돈도 늘어난다
             * @example 2
             */
            riskPerTrade?: number;
            /**
             * Format: int32
             * @description 주당 거래 수
             * @example 2
             */
            tradesPerWeek?: number;
            /**
             * Format: int32
             * @description 시뮬레이션 기간 (주)
             * @example 50
             */
            weeks?: number;
        };
        /**
         * @description N 회 시뮬레이션의 결과 분포
         * @example {
         *       "runs": 1000,
         *       "tradesPerRun": 100,
         *       "expectancyPerTrade": 0.35,
         *       "worstEquity": 594.44,
         *       "percentile5Equity": 956.24,
         *       "medianEquity": 1538.24,
         *       "percentile95Equity": 2474.47,
         *       "bestEquity": 3980.53,
         *       "medianMaxDrawdown": 14.9237,
         *       "worstMaxDrawdown": 42.9287,
         *       "lossProbability": 0.8
         *     }
         */
        MonteCarloResponse: {
            /**
             * Format: int32
             * @description 시행 횟수
             * @example 1000
             */
            runs: number;
            /**
             * Format: int32
             * @description 시행 한 번당 거래 수
             * @example 100
             */
            tradesPerRun: number;
            /**
             * @description 거래당 기댓값을 R 배수로 표현한 값. 0 이면 본전, 음수면 지는 게임이다
             * @example 0.35
             */
            expectancyPerTrade: number;
            /**
             * @description 가장 나빴던 시행의 최종 자산 (USDT)
             * @example 594.44
             */
            worstEquity: number;
            /**
             * @description 하위 5% 시행의 최종 자산. 운이 나쁠 때의 현실적인 바닥
             * @example 956.24
             */
            percentile5Equity: number;
            /**
             * @description 중앙값 시행의 최종 자산
             * @example 1538.24
             */
            medianEquity: number;
            /**
             * @description 상위 5% 시행의 최종 자산
             * @example 2474.47
             */
            percentile95Equity: number;
            /**
             * @description 가장 좋았던 시행의 최종 자산 (USDT)
             * @example 3980.53
             */
            bestEquity: number;
            /**
             * @description 최대낙폭의 중앙값 (%). 절반의 경우 이보다 깊게 빠진다
             * @example 14.9237
             */
            medianMaxDrawdown: number;
            /**
             * @description 가장 깊었던 최대낙폭 (%)
             * @example 42.9287
             */
            worstMaxDrawdown: number;
            /**
             * @description 최종 자산이 초기 자본에 못 미친 시행의 비율 (%)
             * @example 0.8
             */
            lossProbability: number;
        };
        /**
         * @description 표본 경로 요청
         * @example {
         *       "spec": {
         *         "initialCapital": 800,
         *         "winRate": 45,
         *         "riskRewardRatio": 2,
         *         "riskPerTrade": 2,
         *         "tradesPerWeek": 1,
         *         "weeks": 4
         *       },
         *       "seed": 20260821
         *     }
         */
        EquityCurveRequest: {
            /** @description 시뮬레이션 조건 */
            spec?: components["schemas"]["ProjectionSpecRequest"];
            /**
             * Format: int64
             * @description 난수 시드. 같은 시드는 항상 같은 승패 순서를 만든다
             * @example 20260821
             */
            seed?: number;
        };
        /**
         * @description 시드 하나가 만든 자산 곡선
         * @example {
         *       "equity": [
         *         800,
         *         832,
         *         865.28,
         *         899.89,
         *         881.89
         *       ],
         *       "trades": 4,
         *       "finalEquity": 881.89,
         *       "maxDrawdown": 2.0002
         *     }
         */
        EquityCurveResponse: {
            /** @description 거래 순서대로의 자산. 첫 값은 거래 이전의 초기 자본이다 */
            equity: number[];
            /**
             * Format: int32
             * @description 거래 수. 자산 점의 수보다 하나 적다
             * @example 4
             */
            trades: number;
            /**
             * @description 최종 자산 (USDT)
             * @example 881.89
             */
            finalEquity: number;
            /**
             * @description 직전 고점 대비 가장 깊었던 하락폭 (%)
             * @example 2.0002
             */
            maxDrawdown: number;
        };
        /**
         * @description 분할 진입 계획과 계좌 상태
         * @example {
         *       "direction": "LONG",
         *       "entries": [
         *         {
         *           "price": 60000,
         *           "allocation": 50
         *         },
         *         {
         *           "price": 58000,
         *           "allocation": 50
         *         }
         *       ],
         *       "stopLoss": 56000,
         *       "takeProfit": 66000,
         *       "leverage": 10,
         *       "accountBalance": 800,
         *       "riskPercent": 2
         *     }
         */
        AnalyzePositionRequest: {
            /**
             * @description 포지션 방향
             * @example LONG
             * @enum {string}
             */
            direction?: "LONG" | "SHORT";
            /** @description 분할 진입 계획. 50% 분할이면 2건 */
            entries?: components["schemas"]["PositionEntryRequest"][];
            /**
             * @description 손절가. 롱은 최저 진입가보다 낮아야 하고, 숏은 최고 진입가보다 높아야 한다
             * @example 56000
             */
            stopLoss?: number;
            /**
             * @description 익절가. 롱은 최고 진입가보다 높아야 하고, 숏은 최저 진입가보다 낮아야 한다
             * @example 66000
             */
            takeProfit?: number;
            /**
             * Format: int32
             * @description 레버리지 배수. 청산가와 필요 증거금이 이 값에 따라 달라진다
             * @example 10
             */
            leverage?: number;
            /**
             * @description 계좌 잔고 (USDT)
             * @example 800
             */
            accountBalance?: number;
            /**
             * @description 이 거래 한 건에 걸 잔고의 비율. 2 는 2% 를 뜻한다
             * @example 2
             */
            riskPercent?: number;
        };
        /** @description 분할 진입 한 회차. 배열의 순서가 체결될 순서다 */
        PositionEntryRequest: {
            /**
             * @description 이 회차에 지정가 주문을 걸 가격
             * @example 60000
             */
            price?: number;
            /**
             * @description 이 회차에 배정한 비중. 100 이 전액이며 모든 회차의 합이 정확히 100 이어야 한다
             * @example 50
             */
            allocation?: number;
        };
        /** @description n 건까지 체결됐을 때의 포지션 상태 */
        FillStateResponse: {
            /**
             * Format: int32
             * @description 이 시점까지 체결된 진입 회차 수
             * @example 1
             */
            filledEntries: number;
            /**
             * @description 체결된 회차만으로 다시 가중한 평균 진입가
             * @example 60000
             */
            averageEntryPrice: number;
            /**
             * @description 이 시점에 실제로 들고 있는 수량 (BTC)
             * @example 0.00266667
             */
            quantity: number;
            /**
             * @description 이 평단에서의 청산가. 분할 진입은 체결이 진행될수록 이 값이 움직인다
             * @example 54216.87
             */
            liquidationPrice: number;
            /**
             * @description 이 시점에 손절가에 닿았을 때의 손실 (USDT)
             * @example 10.67
             */
            maxLoss: number;
        };
        /**
         * @description 체결 상태별 리스크 산출 결과
         * @example {
         *       "fillStates": [
         *         {
         *           "filledEntries": 1,
         *           "averageEntryPrice": 60000,
         *           "quantity": 0.00266667,
         *           "liquidationPrice": 54216.87,
         *           "maxLoss": 10.67
         *         },
         *         {
         *           "filledEntries": 2,
         *           "averageEntryPrice": 59000,
         *           "quantity": 0.00533333,
         *           "liquidationPrice": 53313.25,
         *           "maxLoss": 16
         *         }
         *       ],
         *       "requiredMargin": 31.47,
         *       "riskRewardRatio": 2.33,
         *       "weakRiskReward": false,
         *       "marginExceedsBalance": false
         *     }
         */
        PositionAnalysisResponse: {
            /** @description 1건 체결부터 전량 체결까지 순서대로. 마지막 원소가 전량 체결 상태다 */
            fillStates: components["schemas"]["FillStateResponse"][];
            /**
             * @description 전량 체결에 필요한 증거금 (USDT)
             * @example 31.47
             */
            requiredMargin: number;
            /**
             * @description 손익비. 익절 거리를 손절 거리로 나눈 값
             * @example 2.33
             */
            riskRewardRatio: number;
            /**
             * @description 손익비가 1.5 미만이라는 경고. 계획을 막지는 않는다
             * @example false
             */
            weakRiskReward: boolean;
            /**
             * @description 필요 증거금이 잔고를 넘어 이 계획을 열 수 없다는 경고
             * @example false
             */
            marginExceedsBalance: boolean;
        };
        /**
         * @description 거래소에서 받아 저장한 결과
         * @example {
         *       "symbol": "BTCUSDT",
         *       "interval": "1h",
         *       "newlyStored": 24
         *     }
         */
        CandleSyncResponse: {
            /**
             * @description 종목
             * @example BTCUSDT
             */
            symbol: string;
            /**
             * @description 캔들 주기
             * @example 1h
             */
            interval: string;
            /**
             * Format: int32
             * @description 새로 저장된 캔들 수. 이미 다 있었다면 0 이다
             * @example 24
             */
            newlyStored: number;
        };
        /** @description 얼마를 걸 것인가 */
        AccountRequest: {
            /**
             * @description 시작 자본 (USDT)
             * @example 800
             */
            initialCapital?: number;
            /**
             * @description 거래당 걸 비율. 손실 크기는 손절가가 아니라 이 값이 정한다
             * @example 2
             */
            riskPercent?: number;
            /**
             * Format: int32
             * @description 레버리지. 증거금과 청산가에만 영향을 준다
             * @example 10
             */
            leverage?: number;
            /**
             * @description FIXED 는 매 거래 초기 자본 기준, COMPOUND 는 직전까지의 자산 기준
             * @example COMPOUND
             * @enum {string}
             */
            capitalMode?: "FIXED" | "COMPOUND";
        };
        /** @description 수수료와 슬리피지. 진입은 maker, 청산은 taker + 슬리피지다 */
        CostsRequest: {
            /**
             * @description 진입 수수료율 (%)
             * @example 0.02
             */
            makerFee?: number;
            /**
             * @description 청산 수수료율 (%)
             * @example 0.05
             */
            takerFee?: number;
            /**
             * @description 청산 체결가가 불리한 쪽으로 밀리는 비율 (%)
             * @example 0.02
             */
            slippage?: number;
        };
        /** @description 신호를 계획으로 바꾸는 규칙 */
        EntryRulesRequest: {
            /**
             * @description 손절을 대 원단에서 얼마나 더 미는가. ATR 의 몇 배
             * @example 1
             */
            stopBufferMultiple?: number;
            /**
             * @description 이 손익비에 못 미치는 계획은 진입하지 않는다
             * @example 1.5
             */
            minRiskReward?: number;
            /**
             * @description 일목·볼린저를 진입 게이트로 쓸 것인가. 끄면 판정을 기록만 한다
             * @example true
             */
            indicatorFilter?: boolean;
        };
        /** @description 지지·저항 반전 백테스트 실행 조건. 같은 요청은 언제나 같은 결과를 낸다 */
        RunBacktestRequest: {
            /**
             * @description 대상 종목. 저장된 캔들이 있어야 한다
             * @example BTCUSDT
             */
            symbol?: string;
            /**
             * @description 캔들 주기. 대 설정이 ATR 배수라 어느 주기든 같은 값으로 돈다
             * @example 4h
             */
            interval?: string;
            /**
             * Format: date-time
             * @description 구간 시작. 워밍업(일목 77봉)만큼 앞의 캔들도 필요하다
             * @example 2026-01-01T00:00:00Z
             */
            from?: string;
            /**
             * Format: date-time
             * @description 구간 끝. 이 시각의 캔들은 포함하지 않는다 (반열림)
             * @example 2026-06-01T00:00:00Z
             */
            to?: string;
            /** @description 대 설정 */
            zones?: components["schemas"]["ZoneSettingsRequest"];
            /** @description 진입 규칙 */
            rules?: components["schemas"]["EntryRulesRequest"];
            /** @description 계좌 설정 */
            account?: components["schemas"]["AccountRequest"];
            /** @description 비용. 생략하면 바이낸스 기본값(maker 0.02% / taker 0.05%) */
            costs?: components["schemas"]["CostsRequest"];
        };
        /** @description 대를 만드는 설정. 전부 봉 수이거나 ATR 배수라 주기에 종속되지 않는다 */
        ZoneSettingsRequest: {
            /**
             * Format: int32
             * @description 스윙 극값 판정에 쓸 좌우 봉 수. 확정 지연도 이 값이다
             * @example 5
             */
            pivotLookback?: number;
            /**
             * @description 같은 대로 묶을 최대 간격. ATR 의 몇 배인가
             * @example 0.5
             */
            clusterMultiple?: number;
            /**
             * Format: int32
             * @description 대로 채택할 최소 터치 수. 피벗 하나는 선이지 대가 아니다
             * @example 2
             */
            minTouches?: number;
            /**
             * Format: int32
             * @description ATR 평활 구간
             * @example 14
             */
            atrPeriod?: number;
        };
        /** @description 백테스트 결과. 성적 요약 · 거래 목록 · 자산 곡선 */
        BacktestResultResponse: {
            /** @description 성적 요약 */
            summary: components["schemas"]["SummaryResponse"];
            /** @description 시간순 거래 전부. 요약만 보고 판단하지 않도록 원자료를 함께 낸다 */
            trades: components["schemas"]["BacktestTradeResponse"][];
            /** @description 거래마다 한 점씩. 첫 점은 거래 이전의 초기 자본이다 */
            equityCurve: number[];
        };
        /** @description 백테스트가 낸 거래 한 건 */
        BacktestTradeResponse: {
            /**
             * @description 방향
             * @example LONG
             * @enum {string}
             */
            direction: "LONG" | "SHORT";
            /**
             * Format: date-time
             * @description 첫 진입 체결 시각
             */
            openedAt: string;
            /**
             * Format: date-time
             * @description 청산 시각
             */
            closedAt: string;
            /**
             * @description 체결 수량 가중 평단
             * @example 59105
             */
            averageEntryPrice: number;
            /**
             * @description 청산가. 슬리피지가 반영돼 있다
             * @example 61987.6
             */
            exitPrice: number;
            /**
             * @description 청산 이유. 백테스트는 계획을 어기지 않으므로 둘뿐이다
             * @example PLANNED_TARGET
             * @enum {string}
             */
            exitReason: "PLANNED_STOP" | "PLANNED_TARGET" | "MANUAL_EARLY" | "HELD_PAST_STOP" | "LIQUIDATED";
            /**
             * Format: int32
             * @description 진입 회차. 1 이면 2차 지정가가 채워지지 않은 채 끝났다
             * @example 2
             */
            filledEntries: number;
            /**
             * @description 수수료를 뺀 실현 손익 (USDT)
             * @example 38.2
             */
            realizedPnl: number;
            /**
             * @description 진입 근거. 어느 대의 어느 경계에서 무엇을 보고 들어갔는가
             * @example 지지대 59000.00~59200.00 (터치 3회) 근단 반전 진입
             */
            rationale: string;
        };
        /** @description 성적 요약 */
        SummaryResponse: {
            /**
             * Format: int32
             * @description 청산까지 끝난 거래 수
             * @example 37
             */
            totalTrades: number;
            /**
             * @description 승률 (%). 0 원으로 끝난 거래는 승리가 아니다
             * @example 62.1621
             */
            winRate: number;
            /**
             * @description 총이익 / 총손실. 진 거래가 없으면 null — 손실이 없는 표본은 손익비를 말할 수 없다
             * @example 1.84
             */
            profitFactor: number | null;
            /**
             * @description 수수료·슬리피지를 뺀 순손익 (USDT)
             * @example 213.45
             */
            netPnl: number;
            /**
             * @description 최종 자산 (USDT)
             * @example 1013.45
             */
            finalEquity: number;
            /**
             * @description 직전 고점 대비 가장 깊었던 하락폭 (%). 사람이 계획을 그만두는 지점은 도착점이 아니라 여기다
             * @example 8.32
             */
            maxDrawdown: number;
        };
        /** @description 백테스트 결과 요약. 문장에 나오는 수는 전부 facts 안의 값이다 */
        BacktestNarrativeResponse: {
            /** @description 한국어 요약. 원본에 없는 수가 들어가면 응답 자체가 만들어지지 않는다 */
            narrative: string;
            /** @description 요약이 쓸 수 있었던 수치 */
            facts: {
                [key: string]: number;
            };
            /** @description 수가 아닌 조건. 종목·주기·구간처럼 대조할 것이 없는 사실 */
            conditions: {
                [key: string]: string;
            };
        };
        /** @description 기준 실행과 변경 실행을 나란히 놓은 결과 */
        ComparisonResponse: {
            /** @description 기준 실행 */
            baseline: components["schemas"]["BacktestResultResponse"];
            /** @description 한 가지를 바꾼 실행 */
            variant: components["schemas"]["BacktestResultResponse"];
            /**
             * @description 순손익 차이. 음수면 그 변경이 손해였다
             * @example -42.1
             */
            pnlDifference: number;
            /**
             * Format: int32
             * @description 거래 수 차이. 필터를 켠 쪽이 줄면 음수
             * @example -11
             */
            tradeDifference: number;
        };
        /**
         * @description 재색인 결과
         * @example {
         *       "indexed": 37
         *     }
         */
        ReindexResponse: {
            /**
             * Format: int32
             * @description 색인된 문서 수. 청산된 거래 하나가 문서 하나다
             * @example 37
             */
            indexed: number;
        };
        /**
         * @description 매매 계획을 적은 자연어 문장
         * @example {
         *       "text": "6만2천에 절반, 6만에 절반 롱. 손절 5만8천, 익절 6만8천, 10배로 간다"
         *     }
         */
        PlanDraftRequest: {
            /**
             * @description 계획을 적은 문장. 빠진 항목은 채워지지 않고 그대로 되물어 온다
             * @example 6만2천에 절반, 6만에 절반 롱. 손절 5만8천, 익절 6만8천, 10배
             */
            text?: string;
        };
        /** @description 분할 진입 한 회차 */
        DraftedPlanEntryResponse: {
            /**
             * @description 이 회차의 지정가
             * @example 62000
             */
            price: number;
            /**
             * @description 이 회차에 넣을 비중. 50 은 50% 를 뜻한다
             * @example 50
             */
            allocation: number;
        };
        /**
         * @description 자연어에서 읽어낸 매매 계획 초안
         * @example {
         *       "direction": "LONG",
         *       "entries": [
         *         {
         *           "price": 62000,
         *           "allocation": 50
         *         },
         *         {
         *           "price": 60000,
         *           "allocation": 50
         *         }
         *       ],
         *       "stopLoss": 58000,
         *       "takeProfit": 68000,
         *       "leverage": 10
         *     }
         */
        PlanDraftResponse: {
            /**
             * @description 포지션 방향
             * @example LONG
             * @enum {string}
             */
            direction: "LONG" | "SHORT";
            /** @description 분할 진입 계획. 문장에 나온 회차 수 그대로다 */
            entries: components["schemas"]["DraftedPlanEntryResponse"][];
            /**
             * @description 손절가
             * @example 58000
             */
            stopLoss: number;
            /**
             * @description 익절가
             * @example 68000
             */
            takeProfit: number;
            /**
             * Format: int32
             * @description 레버리지 배수
             * @example 10
             */
            leverage: number;
        };
        /**
         * @description 매매 기록 질의
         * @example {
         *       "question": "손실 직후에 들어간 거래는 결과가 어땠나?",
         *       "topK": 8
         *     }
         */
        JournalQueryRequest: {
            /**
             * @description 지난 매매에 대한 질문
             * @example 손실 직후에 들어간 거래는 결과가 어땠나?
             */
            question?: string;
            /**
             * Format: int32
             * @description 근거로 볼 거래 수. 1~20, 비우면 8
             * @example 8
             */
            topK?: number;
        };
        /** @description 매매 기록 질의 답변. 인용된 거래는 반드시 검색 결과 안에 있다 */
        JournalAnswerResponse: {
            /** @description 한국어 답변 */
            answer: string;
            /** @description 답변이 근거로 든 거래 식별자 */
            citedTradeIds: string[];
            /** @description 질문에 걸린 거래들. 인용되지 않은 것도 포함한다 */
            retrieved: components["schemas"]["RetrievedTradeResponse"][];
        };
        /** @description 검색된 거래 하나 */
        RetrievedTradeResponse: {
            /** @description 거래 식별자. 이 값으로 원본 기록을 열 수 있다 */
            tradeId: string;
            /**
             * Format: double
             * @description 유사도. 어댑터마다 계산이 다르므로 순서를 읽는 데만 쓴다
             */
            score: number;
            /** @description 색인된 문장. 모델이 본 것도 이것이다 */
            summary: string;
        };
        /** @description 거래 사이의 간격 */
        IntervalsResponse: {
            /**
             * Format: int32
             * @description 센 간격의 수. 거래 수보다 하나 적다
             * @example 3
             */
            gaps: number;
            /**
             * @description 가장 짧았던 간격 (ISO-8601)
             * @example PT12H
             */
            shortest: string;
            /**
             * @description 평균 간격 (ISO-8601)
             * @example PT22H
             */
            average: string;
            /**
             * Format: int32
             * @description 겹쳐서 간격을 셀 수 없었던 쌍의 수. 0 이 아니면 기록이 어긋난 것이다
             * @example 0
             */
            overlaps: number;
        };
        /** @description 계획 준수 여부로 가른 집계 */
        JournalSummaryResponse: {
            /**
             * Format: int32
             * @description 전체 거래 수
             * @example 4
             */
            totalTrades: number;
            /**
             * @description 전체 실현 손익 (USDT)
             * @example 288.8
             */
            totalRealizedPnl: number;
            /**
             * @description 계획대로 닫은 거래의 비율 (%)
             * @example 50
             */
            planAdherence: number;
            /** @description 계획을 지킨 거래들 */
            followed: components["schemas"]["TallyResponse"];
            /** @description 계획을 어긴 거래들 */
            broken: components["schemas"]["TallyResponse"];
            /**
             * @description 어긴 거래들을 손절가에서 닫았다면 났을 손익 합
             * @example -310
             */
            lossIfEveryStopHonored: number;
            /**
             * @description 계획을 어겨서 얻은 것의 합. 음수면 어기는 편이 손해였다
             * @example -206
             */
            costOfDeviation: number;
            /** @description 거래 사이의 간격 */
            intervals: components["schemas"]["IntervalsResponse"];
        };
        /** @description 거래 한 무리의 건수·손익·승률 */
        TallyResponse: {
            /**
             * Format: int32
             * @description 건수
             * @example 2
             */
            trades: number;
            /**
             * @description 실현 손익 합 (USDT)
             * @example 288.8
             */
            realizedPnl: number;
            /**
             * Format: int32
             * @description 이긴 건수. 본전은 승리가 아니다
             * @example 1
             */
            wins: number;
            /**
             * Format: int32
             * @description 진 건수
             * @example 1
             */
            losses: number;
            /**
             * @description 승률 (%)
             * @example 50
             */
            winRate: number;
        };
        /**
         * @description 한 시점의 펀딩비·미결제약정·롱숏비율
         * @example {
         *       "symbol": "BTCUSDT",
         *       "at": "2026-08-21T08:00:00Z",
         *       "fundingRatePercent": 0.01,
         *       "openInterest": 81234.5,
         *       "longShortRatio": 1.8342
         *     }
         */
        MarketMetricsResponse: {
            /**
             * @description 종목
             * @example BTCUSDT
             */
            symbol: string;
            /**
             * Format: date-time
             * @description 이 값들의 관측 시각
             * @example 2026-08-21T08:00:00Z
             */
            at: string;
            /**
             * @description 펀딩비 (%). 음수면 숏이 롱에게 낸다
             * @example 0.01
             */
            fundingRatePercent: number;
            /**
             * @description 미결제약정 (BTC). 늘면서 가격이 오르면 신규 롱이 들어온 것이다
             * @example 81234.5
             */
            openInterest: number;
            /**
             * @description 롱 계정 수 / 숏 계정 수. 금액이 아니라 계정 수 기준이다
             * @example 1.8342
             */
            longShortRatio: number;
        };
        /** @description 한 구간의 시가·고가·저가·종가와 거래량 */
        CandleResponse: {
            /**
             * Format: date-time
             * @description 구간 시작 시각 (UTC)
             * @example 2026-08-01T00:00:00Z
             */
            openTime: string;
            /**
             * @description 시가 (USDT)
             * @example 60000
             */
            open: number;
            /**
             * @description 고가 (USDT). 시가·저가·종가를 모두 감싼다
             * @example 61000
             */
            high: number;
            /**
             * @description 저가 (USDT)
             * @example 59000
             */
            low: number;
            /**
             * @description 종가 (USDT)
             * @example 60500
             */
            close: number;
            /**
             * @description 거래량 (BTC). 거래가 없던 구간은 0 이다
             * @example 1.5
             */
            volume: number;
        };
        /**
         * @description 저장된 캔들 묶음. 시간 오름차순이고 같은 시각이 두 번 나타나지 않는다
         * @example {
         *       "symbol": "BTCUSDT",
         *       "interval": "1h",
         *       "count": 2,
         *       "candles": [
         *         {
         *           "openTime": "2026-08-01T00:00:00Z",
         *           "open": 60000,
         *           "high": 61000,
         *           "low": 59000,
         *           "close": 60500,
         *           "volume": 1.5
         *         },
         *         {
         *           "openTime": "2026-08-01T01:00:00Z",
         *           "open": 60000,
         *           "high": 61000,
         *           "low": 59000,
         *           "close": 60501,
         *           "volume": 1.5
         *         }
         *       ]
         *     }
         */
        CandleSeriesResponse: {
            /**
             * @description 종목
             * @example BTCUSDT
             */
            symbol: string;
            /**
             * @description 캔들 주기
             * @example 1h
             */
            interval: string;
            /**
             * Format: int32
             * @description 캔들 수. 요청 구간이 기대하는 수보다 적으면 수집에 구멍이 있다
             * @example 2
             */
            count: number;
            /** @description 캔들 목록 */
            candles: components["schemas"]["CandleResponse"][];
        };
        /** @description 거래소가 말하는 지금 이 순간의 포지션 */
        ExchangeSideResponse: {
            /**
             * @description 종목
             * @example BTCUSDT
             */
            symbol: string;
            /**
             * @description 거래소가 계산한 평단
             * @example 59500
             */
            entryPrice: number;
            /**
             * @description 보유 수량. 언제나 양수이고 방향은 따로 있다
             * @example 0.1
             */
            quantity: number;
            /**
             * @description 거래소가 계산한 청산가. 우리 계산과 대조할 수 있는 유일한 값이다.
             *     거래소가 청산 지점을 말할 수 없으면 null 이다 — 0 은 청산가가 아니라 '없음'이다.
             * @example 53765.06
             */
            liquidationPrice: number | null;
            /**
             * @description 미실현 손익. 기록에는 없는 값이다 — 매 순간 달라지므로 기록의 대상이 아니다
             * @example 12.4
             */
            unrealizedPnl: number;
        };
        /** @description 한 방향의 기록과 거래소를 맞춰 본 한 줄 */
        PositionMatchResponse: {
            /**
             * @description 이 줄이 어느 방향의 포지션에 대한 것인가
             * @example LONG
             */
            direction: string;
            /**
             * @description 맞춰 본 결과.
             *     AGREED 는 방향과 수량이 같다.
             *     RECORDED_ONLY 는 기록에는 열려 있는데 거래소에 없다 — 청산을 적지 않았을 수 있다.
             *     EXCHANGE_ONLY 는 거래소에 있는데 기록에 없다 — 앱 밖에서 열었다.
             *     QUANTITY_DIFFERS 는 둘 다 있는데 수량이 다르다 — 물타기나 부분 청산이 안 적혔다.
             * @example AGREED
             */
            outcome: string;
            /**
             * @description 사람이 확인할 것이 있는가
             * @example false
             */
            discrepancy: boolean;
            /** @description 기록 쪽. 거래소에만 있는 포지션이면 null 이다 */
            recorded: components["schemas"]["RecordedSideResponse"] | null;
            /** @description 거래소 쪽. 기록에만 있는 거래면 null 이다 */
            actual: components["schemas"]["ExchangeSideResponse"] | null;
        };
        /** @description 기록의 미청산 거래와 거래소 포지션을 방향으로 맞춰 본 결과 */
        PositionReconciliationResponse: {
            /** @description 방향마다 한 줄. 짝이 지어지지 않은 쪽도 한 줄이다 */
            matches: components["schemas"]["PositionMatchResponse"][];
            /**
             * @description 확인할 것이 하나도 없는가. 양쪽 모두 비어 있어도 참이다
             * @example true
             */
            consistent: boolean;
            /**
             * Format: date-time
             * @description 거래소 값을 읽은 시각. 이 값은 다음 순간이면 달라진다
             * @example 2026-08-23T01:53:00Z
             */
            observedAt: string;
        };
        /** @description 기록에 남아 있는 미청산 거래 */
        RecordedSideResponse: {
            /**
             * Format: uuid
             * @description 거래 식별자
             * @example 3f2a1c8e-5b7d-4e9f-a1b2-c3d4e5f60718
             */
            tradeId: string;
            /**
             * @description 실제 체결 평단. 계획한 평단과 다를 수 있고 그 차이가 슬리피지다
             * @example 59500
             */
            averageEntryPrice: number;
            /**
             * @description 체결된 총수량
             * @example 0.1
             */
            quantity: number;
            /**
             * @description 계획한 모든 분할이 체결됐는가
             * @example true
             */
            fullyFilled: boolean;
            /**
             * Format: date-time
             * @description 포지션이 열린 시각. 첫 체결이다
             * @example 2026-08-01T01:00:00Z
             */
            openedAt: string;
        };
        /** @description 오류 본문(RFC 7807). detail 에 도메인이 쓴 문장이 그대로 들어간다 */
        ProblemDetail: {
            /** @description 오류 종류를 가리키는 URI. about:blank 이면 아예 오지 않는다 */
            type?: string;
            /** @description 오류 분류. 사람이 읽는 짧은 이름 */
            title: string;
            /**
             * Format: int32
             * @description HTTP 상태 코드
             */
            status: number;
            /** @description 무엇이 왜 안 됐는가. 화면은 이 문장을 그대로 보여준다 */
            detail: string;
            /** @description 오류가 난 요청 경로 */
            instance: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    closedTrades: {
        parameters: {
            query?: {
                /**
                 * @description 이 시각부터 (포함)
                 * @example 2026-08-01T00:00:00Z
                 */
                closedFrom?: string;
                /**
                 * @description 이 시각까지 (제외)
                 * @example 2026-09-01T00:00:00Z
                 */
                closedTo?: string;
                /**
                 * @description 포지션 방향
                 * @example LONG
                 */
                direction?: "LONG" | "SHORT";
                /**
                 * @description 청산 이유
                 * @example HELD_PAST_STOP
                 */
                exitReason?: "PLANNED_STOP" | "PLANNED_TARGET" | "MANUAL_EARLY" | "HELD_PAST_STOP" | "LIQUIDATED";
                /**
                 * @description 계획 준수 여부
                 * @example false
                 */
                followedPlan?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TradeResponse"][];
                };
            };
        };
    };
    plan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradePlanRequest"];
            };
        };
        responses: {
            /** @description 저장됨. 이후 요청에 쓸 식별자를 돌려준다 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TradeResponse"];
                };
            };
            /** @description 값 자체가 부적절하다 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description 계획으로 성립하지 않는다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    recordFills: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordFillsRequest"];
            };
        };
        responses: {
            /** @description OPEN 으로 넘어간 거래 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TradeResponse"];
                };
            };
            /** @description 그런 거래가 없다 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description 계획 상태가 아니거나 체결이 계획보다 앞선다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    close: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseTradeRequest"];
            };
        };
        responses: {
            /** @description CLOSED 로 넘어간 거래. 손익은 도메인이 계산해 채운다 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TradeResponse"];
                };
            };
            /** @description 그런 거래가 없다 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description 열려 있지 않거나 청산이 진입보다 앞선다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    monteCarlo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonteCarloRequest"];
            };
        };
        responses: {
            /** @description 백분위 다섯 점과 손실 확률, 최대낙폭 분포 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MonteCarloResponse"];
                };
            };
            /** @description 값 자체가 부적절하다. 0 이하의 시행 횟수, 누락된 필드 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description 값은 유효하나 조건으로 성립하지 않는다. 시행 횟수나 총 거래 수 상한 초과 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    equityCurve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EquityCurveRequest"];
            };
        };
        responses: {
            /** @description 거래마다 한 점인 자산 곡선. 첫 점이 초기 자본이다 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EquityCurveResponse"];
                };
            };
            /** @description 값 자체가 부적절하다. 음수 자본, 100% 를 넘는 승률, 누락된 필드 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description 값은 유효하나 조건으로 성립하지 않는다. 총 거래 수 상한 초과 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    analyze: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzePositionRequest"];
            };
        };
        responses: {
            /** @description 체결 상태별 평단 · 수량 · 청산가 · 최대손실, 그리고 필요 증거금과 손익비 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PositionAnalysisResponse"];
                };
            };
            /** @description 값 자체가 부적절하다. 음수 가격, 누락된 필드, 0 이하의 잔고 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description 값은 유효하나 계획으로 성립하지 않는다. 손절가 방향 오류, 비중 합 불일치, 손절가가 청산가 너머 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    sync: {
        parameters: {
            query: {
                interval: string;
                from: string;
                to: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 가져온 캔들 수와 저장된 수. 이미 있던 것은 다시 세지 않는다 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CandleSyncResponse"];
                };
            };
            /** @description 종목 표기나 캔들 주기가 올바르지 않다 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description 구간의 끝이 시작보다 앞이다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description 거래소에 닿지 못했다 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunBacktestRequest"];
            };
        };
        responses: {
            /** @description 요약 수치 · 거래 목록 · 자산 곡선 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BacktestResultResponse"];
                };
            };
            /** @description 값 자체가 부적절하다. 알 수 없는 주기, 음수 자본, 뒤집힌 구간 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description 값은 유효하나 백테스트로 성립하지 않는다. 워밍업(일목 77봉)을 채우지 못하는 구간, 터치 2회 미만의 대 설정 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    narrate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunBacktestRequest"];
            };
        };
        responses: {
            /** @description 요약 문장과 그 문장이 쓴 수의 출처인 facts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BacktestNarrativeResponse"];
                };
            };
            /** @description AI 기능이 설정되지 않았거나(OPENAI_API_KEY), 모델이 원본에 없는 수를 썼다. 둘 다 사용자가 고칠 것이 아니라 다시 시도할 일이다 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    compareIndicatorFilter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunBacktestRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ComparisonResponse"];
                };
            };
        };
    };
    compareCosts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunBacktestRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ComparisonResponse"];
                };
            };
        };
    };
    reindex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 다시 색인한 거래 건수 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReindexResponse"];
                };
            };
            /** @description AI 기능이 설정되지 않았다 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    draftPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanDraftRequest"];
            };
        };
        responses: {
            /** @description 문장에서 읽어낸 계획 초안. 폼을 채울 뿐 제출하지 않는다 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PlanDraftResponse"];
                };
            };
            /** @description 문장이 비어 있다 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description 문장에서 읽어내지 못한 항목이 있거나, 읽어낸 값이 계획으로 성립하지 않는다. 응답 본문이 무엇이 빠졌는지 알려 준다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description AI 기능이 설정되지 않았다. OPENAI_API_KEY 가 필요하다 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    askJournal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JournalQueryRequest"];
            };
        };
        responses: {
            /** @description 답변과 근거 거래 식별자. 원본 기록과 대조할 수 있다 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JournalAnswerResponse"];
                };
            };
            /** @description 질문이 비었거나 근거 거래 수가 범위 밖이다 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description AI 기능이 설정되지 않았거나, 답변이 검색되지 않은 거래를 인용했다 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    trade: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 거래 한 건의 현재 상태 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TradeResponse"];
                };
            };
            /** @description 그런 거래가 없다 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    summary: {
        parameters: {
            query?: {
                /**
                 * @description 이 시각부터 (포함)
                 * @example 2026-08-01T00:00:00Z
                 */
                closedFrom?: string;
                /**
                 * @description 이 시각까지 (제외)
                 * @example 2026-09-01T00:00:00Z
                 */
                closedTo?: string;
                /**
                 * @description 포지션 방향
                 * @example LONG
                 */
                direction?: "LONG" | "SHORT";
                /**
                 * @description 청산 이유
                 * @example HELD_PAST_STOP
                 */
                exitReason?: "PLANNED_STOP" | "PLANNED_TARGET" | "MANUAL_EARLY" | "HELD_PAST_STOP" | "LIQUIDATED";
                /**
                 * @description 계획 준수 여부
                 * @example false
                 */
                followedPlan?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JournalSummaryResponse"];
                };
            };
        };
    };
    activeTrades: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TradeResponse"][];
                };
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 펀딩비 · 미결제약정 · 롱숏비율 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MarketMetricsResponse"];
                };
            };
            /** @description 종목 표기가 올바르지 않다 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description 거래소에 닿지 못했다 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    candles: {
        parameters: {
            query: {
                interval: string;
                from: string;
                to: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 저장된 캔들. 구간에 없으면 빈 목록이다 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CandleSeriesResponse"];
                };
            };
            /** @description 종목 표기나 캔들 주기가 올바르지 않다 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description 구간의 끝이 시작보다 앞이다 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    positions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 방향별 대조 결과 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PositionReconciliationResponse"];
                };
            };
            /** @description 거래소 계정이 연결되지 않았거나 거래소를 읽지 못했다. COINWIN_ACCOUNT_BINANCE_API_KEY 와 SECRET_KEY 가 필요하다 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
}
